### PR TITLE
build: Update GNOME runtime to 42

### PR DESCRIPTION
**Pull request by BigmenPixel0**

### CODE REVIEW

**Comment by fushinari** [comment]
There will be a new release soon.

If you'd like to help out, you can review the new strings in https://github.com/dialect-app/po/pull/12 . We will be making an issue regarding it in the main repo soon.

**Comment by tinywrkb** [comment]
@fushinari Gnome 42 was rebased on Freedesktop 21.08.13 while Gnome 41 is still on 21.08.12, which is missing [this backport to harfbuzz](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/7971).  
I have broken CJK glyphs with 41, but no issue when building the app with 42.  
I highly suggest decoupling runtime bumps from application release updates.

**Comment by fushinari** [comment]
@tinywrkb Normally, we bump the runtime version only with new application releases or when the current runtime becomes EOL. Of course, if there is an issue caused by the current runtime version, we will bump the runtime version too. In this case, we were not aware of the issue you mentioned, but now that I know, I will be merging this. If you find any such issue in the future, please feel free to let us know :)

**Comment by tinywrkb** [comment]
@fushinari thanks!

> Normally, we bump the runtime version only with new application releases or when the current runtime becomes EOL.

Not the best approach. If the runtime was marked as EOL, then it's already unmaintained, might have security vulnerabilities, and it got to a point where Flatpak outputs a warning to the user about the application.

**Comment by rafaelmardojai** [comment]
> Not the best approach. If the runtime was marked as EOL, then it's already unmaintained, might have security vulnerabilities, and it got to a point where Flatpak outputs a warning to the user about the application.

Well we try to do it before the runtime is actually EOL.

**Pull request merged**
